# Generated by Django 5.2.6 on 2025-09-26 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('has_cc_range', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_ambulance', models.BooleanField(default=False)),
                ('needs_income_tax', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CCRange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_cc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_cc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.category')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('days_count', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.fiscalyear')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vehicle_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renewal_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.category')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.fiscalyear')),
                ('reg_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.regtype')),
            ],
        ),
    ]
