# Generated by Django 5.2.6 on 2025-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regtype',
            name='name_en',
            field=models.CharField(default='edit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regtype',
            name='tax_rate',
            field=models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('PUBLIC', 'PUBLIC'), ('FREE', 'FREE'), ('RENEW_ONLY', 'RENEW_ONLY')], default='PRIVATE', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='has_cc_range',
            field=models.BooleanField(default=False, verbose_name='Has CC/Watt range?'),
        ),
        migrations.AlterField(
            model_name='ccrange',
            name='from_cc',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='From CC/W/KW'),
        ),
        migrations.AlterField(
            model_name='ccrange',
            name='to_cc',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='To CC/W/KW'),
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
