# Generated by Django 5.2.6 on 2025-09-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_category_name_en_regtype_name_en_regtype_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='name_en',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
