# Generated by Django 5.2.6 on 2025-09-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_fiscalyear_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regtype',
            old_name='tax_rate',
            new_name='tax_type',
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tax_type',
            field=models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('PUBLIC', 'PUBLIC'), ('FREE', 'FREE'), ('RENEW_ONLY', 'RENEW_ONLY')], default='PRIVATE', max_length=100),
        ),
    ]
