# Generated by Django 5.2.6 on 2025-09-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_incometaxrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccrange',
            name='for_income_tax',
            field=models.BooleanField(default=False),
        ),
    ]
