# Generated by Django 5.2.6 on 2025-09-26 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_ccrange_for_income_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrate',
            name='cc',
        ),
        migrations.AddField(
            model_name='taxrate',
            name='cc_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.ccrange'),
        ),
    ]
