# Generated by Django 5.2.6 on 2025-09-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_remove_taxrate_cc_taxrate_cc_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrate',
            name='income_tax',
        ),
    ]
