# Generated by Django 5.2.6 on 2025-09-26 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_remove_taxrate_income_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='next_fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextfy', to='calc.fiscalyear'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='previous_fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previousfy', to='calc.fiscalyear'),
        ),
    ]
