# Generated by Django 5.2.6 on 2025-09-26 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_fiscalyear_next_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='income_tax_due_date',
            field=models.DateField(default=datetime.date(2025, 9, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='vehicle_tax_due_date',
            field=models.DateField(default=datetime.date(2025, 9, 26)),
            preserve_default=False,
        ),
    ]
