# Generated by Django 5.2.6 on 2025-09-27 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_fiscalyear_income_tax_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalyear',
            name='next_fiscal_year',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='previous_fiscal_year',
        ),
        migrations.RemoveField(
            model_name='regtype',
            name='tax_type',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='tax_type',
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='calc.fiscalyear'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='income_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='IncomeTaxRate',
        ),
    ]
