# Generated by Django 5.2.6 on 2025-09-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_remove_fiscalyear_next_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='name_en',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='regtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='regtype',
            name='name_en',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
