# Generated by Django 5.2.6 on 2025-09-27 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_alter_category_name_alter_category_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regtype',
            name='is_ambulance',
        ),
        migrations.RemoveField(
            model_name='regtype',
            name='needs_income_tax',
        ),
        migrations.AddField(
            model_name='category',
            name='reg_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='calc.regtype'),
        ),
        migrations.CreateModel(
            name='RegRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_exempted', models.BooleanField(default=False)),
                ('renewal_exempted', models.BooleanField(default=False)),
                ('income_tax_exempted', models.BooleanField(default=False)),
                ('regtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calc.regtype')),
            ],
        ),
    ]
