# Generated by Django 5.2.6 on 2025-09-27 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_remove_regtype_is_ambulance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccrange',
            name='fiscal_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='calc.fiscalyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regrule',
            name='fiscal_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='calc.fiscalyear'),
            preserve_default=False,
        ),
    ]
