# Generated by Django 5.2.6 on 2025-09-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_ccrange_fiscal_year_regrule_fiscal_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
        ),
    ]
