# Generated by Django 5.2.6 on 2025-09-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccrange',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='calc.province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regrule',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='calc.province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxrate',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='calc.province'),
            preserve_default=False,
        ),
    ]
