# Generated by Django 5.2.6 on 2025-09-27 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_ccrange_province_regrule_province_taxrate_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrate',
            name='income_tax',
        ),
        migrations.CreateModel(
            name='IncomeTaxRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('income_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.category')),
                ('cc_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.ccrange')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.fiscalyear')),
                ('reg_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.regtype')),
            ],
        ),
    ]
