# Generated by Django 5.2.6 on 2025-09-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0017_remove_taxrate_income_tax_incometaxrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='calc.fiscalyear'),
        ),
        migrations.AddField(
            model_name='category',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='calc.province'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next', to='calc.fiscalyear'),
        ),
    ]
