# Generated by Django 5.2.6 on 2025-09-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0018_category_fiscal_year_category_province_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxrate',
            old_name='renewal_fee',
            new_name='private_renewal',
        ),
        migrations.RenameField(
            model_name='taxrate',
            old_name='vehicle_tax',
            new_name='private_tax',
        ),
        migrations.RemoveField(
            model_name='category',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='category',
            name='province',
        ),
        migrations.AddField(
            model_name='taxrate',
            name='public_renewal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxrate',
            name='public_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
