# Generated by Django 5.2.6 on 2025-09-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0019_rename_renewal_fee_taxrate_private_renewal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='reg_type',
        ),
    ]
