# Generated by Django 5.2.6 on 2025-09-29 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0020_remove_category_reg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccrange',
            name='reg_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='calc.regtype'),
            preserve_default=False,
        ),
    ]
